Add 180 minutes timeout to SLFO product building pipelines.

diff --git a/gocd/slfo-stagings.gocd.yaml.erb b/gocd/slfo-stagings.gocd.yaml.erb
--- a/gocd/slfo-stagings.gocd.yaml.erb
+++ b/gocd/slfo-stagings.gocd.yaml.erb
@@ -123,14 +123,19 @@ pipelines:
           - staging-bot
         tasks:
           - script: |-
+              minutes=0
               osc -A $STAGING_API api -X POST "/source/$STAGING_PROJECT?cmd=remove_flag&repository=product&flag=build"
               export PYTHONPATH=$PWD/scripts
               while ./scripts/gocd/verify-repo-built-successful.py -A $STAGING_API -p $STAGING_PROJECT -r product; ret=$?; [ ${ret} -ne 0 ]; do
                 if [ ${ret} -eq 2 ]; then
                     echo "product repository not found. Project configuration issue?" >&2
                     exit 1
+                elif [ ${minutes} -gt 180 ]; then
+                    echo "Product is still failing after timeout, exiting..." >&2
+                    exit 1
                 fi
                 sleep 60
+                minutes=$(expr $minutes + 1)
               done
 
     - Enable.images.repo:
@@ -268,14 +273,19 @@ pipelines:
           - staging-bot
         tasks:
           - script: |-
+              minutes=0
               osc -A $STAGING_API api -X POST "/source/$STAGING_PROJECT?cmd=remove_flag&repository=product&flag=build"
               export PYTHONPATH=$PWD/scripts
               while ./scripts/gocd/verify-repo-built-successful.py -A $STAGING_API -p $STAGING_PROJECT -r product; ret=$?; [ ${ret} -ne 0 ]; do
                 if [ ${ret} -eq 2 ]; then
                     echo "product repository not found. Project configuration issue?" >&2
                     exit 1
+                elif [ ${minutes} -gt 180 ]; then
+                    echo "Product is still failing after timeout, exiting..." >&2
+                    exit 1
                 fi
                 sleep 60
+                minutes=$(expr $minutes + 1)
               done
 
     - Enable.images.repo:
